### ISSUE TITLE
Error: Cannot find module 'nightwatch-helpers'

### ISSUE THREAD

**Issue by fourcels** [vuejs/vue-router#1097]
debian: 8.6
node: v6.9.1
vue-router: 2.1.1

```
# clone vue-router
git clone https://github.com/vuejs/vue-router.git

# install deps
npm install

# serve examples at localhost:8080
npm run dev
resolve failed:  { Error: Cannot find module 'nightwatch-helpers'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.requireRelative.resolve (/home/kiyan/Documents/vue-router/node_modules/require-relative/index.js:30:17)
    at resolve (/home/kiyan/Documents/vue-router/node_modules/modify-babel-preset/lib/serialize.js:26:26)
    at findAndRemove (/home/kiyan/Documents/vue-router/node_modules/modify-babel-preset/lib/serialize.js:83:11)

    at /home/kiyan/Documents/vue-router/node_modules/modify-babel-preset/lib/serialize.js:126:13
    at Array.map (native)
    at loadPreset (/home/kiyan/Documents/vue-router/node_modules/modify-babel-preset/lib/serialize.js:118:29)
    at module.exports (/home/kiyan/Documents/vue-router/node_modules/modify-babel-preset/index.js:95:19)
    at Object.<anonymous> (/home/kiyan/Documents/vue-router/node_modules/babel-preset-es2015-loose/index.js:5:18)
    at Module._compile (module.js:570:32) code: 'MODULE_NOT_FOUND' } nightwatch-helpers
resolve failed:  { Error: Cannot find module 'caniuse-db'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.requireRelative.resolve (/home/kiyan/Documents/vue-router/node_modules/require-relative/index.js:30:17)
    at resolve (/home/kiyan/Documents/vue-router/node_modules/modify-babel-preset/lib/serialize.js:26:26)
    at findAndRemove (/home/kiyan/Documents/vue-router/node_modules/modify-babel-preset/lib/serialize.js:83:11)
    at /home/kiyan/Documents/vue-router/node_modules/modify-babel-preset/lib/serialize.js:126:13
    at Array.map (native)
    at loadPreset (/home/kiyan/Documents/vue-router/node_modules/modify-babel-preset/lib/serialize.js:118:29)
    at module.exports (/home/kiyan/Documents/vue-router/node_modules/modify-babel-preset/index.js:95:19)
    at Object.<anonymous> (/home/kiyan/Documents/vue-router/node_modules/babel-preset-es2015-loose/index.js:5:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19) code: 'MODULE_NOT_FOUND' } caniuse-db
resolve failed:  { Error: Cannot find module 'babel-runtime'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.requireRelative.resolve (/home/kiyan/Documents/vue-router/node_modules/require-relative/index.js:30:17)
    at resolve (/home/kiyan/Documents/vue-router/node_modules/modify-babel-preset/lib/serialize.js:26:26)
    at findAndRemove (/home/kiyan/Documents/vue-router/node_modules/modify-babel-preset/lib/serialize.js:83:11)
    at /home/kiyan/Documents/vue-router/node_modules/modify-babel-preset/lib/serialize.js:126:13
    at Array.map (native)
    at loadPreset (/home/kiyan/Documents/vue-router/node_modules/modify-babel-preset/lib/serialize.js:118:29)
    at module.exports (/home/kiyan/Documents/vue-router/node_modules/modify-babel-preset/index.js:95:19)
    at Object.<anonymous> (/home/kiyan/Documents/vue-router/node_modules/babel-preset-es2015-loose/index.js:5:18)
    at Module._compile (module.js:570:32)

    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19) code: 'MODULE_NOT_FOUND' } babel-runtime
resolve failed:  { Error: Cannot find module 'webpack-core'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.requireRelative.resolve (/home/kiyan/Documents/vue-router/node_modules/require-relative/index.js:30:17)
    at resolve (/home/kiyan/Documents/vue-router/node_modules/modify-babel-preset/lib/serialize.js:26:26)
    at findAndRemove (/home/kiyan/Documents/vue-router/node_modules/modify-babel-preset/lib/serialize.js:83:11)
    at /home/kiyan/Documents/vue-router/node_modules/modify-babel-preset/lib/serialize.js:126:13
    at Array.map (native)
    at loadPreset (/home/kiyan/Documents/vue-router/node_modules/modify-babel-preset/lib/serialize.js:118:29)
    at module.exports (/home/kiyan/Documents/vue-router/node_modules/modify-babel-preset/index.js:95:19)
    at Object.<anonymous> (/home/kiyan/Documents/vue-router/node_modules/babel-preset-es2015-loose/index.js:5:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19) code: 'MODULE_NOT_FOUND' } webpack-core
```

Edit .babelrc file `es2015-loose` to `es2015`, the error disappeared
```json
{
  "presets": ["es2015", "flow-vue"]
}
```

**Comment by posva** [comment]
Use yarn to install instead, it's more reliable.
I tested locally (reinstall node_modules) and works fine

**Comment by fourcels** [comment]
I have used yarn to install
but it show some resolve failed

```
node 6.10.0
yarn 0.21.3
vue-router 2.3.0
```

``` bash
~/Documents/vue-router (dev ✔) ᐅ npm run dev

> vue-router@2.3.0 dev /home/kiyan/Documents/vue-router
> node examples/server.js

Server listening on http://localhost:8080, Ctrl+C to stop
resolve failed for "nightwatch-helpers": Error: Cannot find module 'nightwatch-helpers'
resolve failed for "caniuse-db": Error: Cannot find module 'caniuse-db'
resolve failed for "babel-runtime": Error: Cannot find module 'babel-runtime'
Hash: c247543f95bc41757d20
Version: webpack 2.2.1
Time: 4888ms
                 Asset     Size  Chunks                    Chunk Names
      nested-routes.js  9.84 kB      10  [emitted]         nested-routes
            0.chunk.js  14.6 kB       0  [emitted]         /bar
          auth-flow.js  75.8 kB       2  [emitted]         auth-flow
      data-fetching.js  53.4 kB       3  [emitted]         data-fetching
        route-props.js  13.9 kB       4  [emitted]         route-props
        transitions.js  6.68 kB       5  [emitted]         transitions
    scroll-behavior.js  7.23 kB       6  [emitted]         scroll-behavior
     route-matching.js   6.3 kB       7  [emitted]         route-matching
        route-alias.js  7.34 kB       8  [emitted]         route-alias
           redirect.js  10.8 kB       9  [emitted]         redirect
            1.chunk.js  8.78 kB       1  [emitted]         
  navigation-guards.js  13.7 kB      11  [emitted]         navigation-guards
        named-views.js  4.38 kB      12  [emitted]         named-views
       named-routes.js   4.1 kB      13  [emitted]         named-routes
       lazy-loading.js  8.52 kB      14  [emitted]         lazy-loading
          hash-mode.js  4.59 kB      15  [emitted]         hash-mode
discrete-components.js  4.66 kB      16  [emitted]         discrete-components
              basic.js  4.63 kB      17  [emitted]         basic
       active-links.js  6.81 kB      18  [emitted]         active-links
             shared.js   924 kB      19  [emitted]  [big]  shared
webpack: Compiled successfully.

```
