### ISSUE TITLE
"Cannot read property ‘name’ of undefined" – vue-router works as long as I don't use router-link component

### ISSUE THREAD

**Issue by adamdehaven** [vuejs/vue-router#2652]
### Version
3.0.2

### Reproduction link
[https://codesandbox.io/s/6w7y01qo5z?fontsize=14](https://codesandbox.io/s/6w7y01qo5z?fontsize=14)

### Steps to reproduce
I’ve created a CodeSandbox with my relevant files, however, the bug does not happen in the CodeSandbox or when I run locally. Only when I embed my code in the environment in which it needs to run, I receive the following error:

![TypeError](https://forum.vuejs.org/uploads/default/original/3X/b/8/b8146297ebe50cd3b4c26d08d1318e826e48bd84.png)

If I click on the first call in the stack, here’s the line that’s throwing the error:

![Error Line](https://forum.vuejs.org/uploads/default/original/3X/0/b/0b0ab3249aa249d8754db0ac3427b30dd0e956ca.png)

The `<router-link>` items do not render on the page, however the rest of my Vue app (anything that is not related to vue-router) works fine.

Once the page is loaded, if I manually change the URL to `/foo`, the links will then appear, and work as expected.

The error only occurs when there is a `<router-link>` element on the page. If I create a function and attach it to a click event (e.g. on a Button) such as shown below, I have no issues. This literally only errors when I use the `<router-link>` element:

```
methods: {
    ...
    onButtonClick() {
        // This works fine; no errors!
        this.$router.push({ name: 'bar' })
    }
}
```

It also works perfectly if I put the function directly on `<a/>` element:

`<a href="#" @click.prevent="$router.push({ name: 'Foo' })">Foo</a>`

 

### What is expected?
The `<router-link>` component should render properly on load, without error.

### What is actually happening?
If there is a `<router-link>` component on the page, the error (referenced above) appears. If I use `this.$router.push()` there are no issues.

---
The related Vue JS Forum post can be found here: https://forum.vuejs.org/t/cannot-read-property-name-of-undefined-works-locally-but-not-in-production-environment/58975

**Comment by posva** [comment]
If the problem doesn't appear in the repro I cannot check it, sorry

**Comment by adamdehaven** [comment]
@posva I've updated the demo. You can see the error in the console: https://codesandbox.io/s/7mooxvokz1

```
TypeError: Cannot read property 'name' of undefined
    at normalizeLocation (https://7mooxvokz1.codesandbox.io/node_modules/vue-router/dist/vue-router.common.js:1275:12)

    at Object.match (https://7mooxvokz1.codesandbox.io/node_modules/vue-router/dist/vue-router.common.js:1343:20)

    at VueRouter.match (https://7mooxvokz1.codesandbox.io/node_modules/vue-router/dist/vue-router.common.js:2463:23)

    at HashHistory.transitionTo (https://7mooxvokz1.codesandbox.io/node_modules/vue-router/dist/vue-router.common.js:1867:27)

    at HashHistory.replace (https://7mooxvokz1.codesandbox.io/node_modules/vue-router/dist/vue-router.common.js:2281:10)

    at VueRouter.replace (https://7mooxvokz1.codesandbox.io/node_modules/vue-router/dist/vue-router.common.js:2535:16)

    at VueComponent.mounted (https://7mooxvokz1.codesandbox.io/src/App.vue?33fd1cc2:26:48)

    at invokeWithErrorHandling (https://7mooxvokz1.codesandbox.io/node_modules/vue/dist/vue.common.dev.js:1859:57)

    at callHook (https://7mooxvokz1.codesandbox.io/node_modules/vue/dist/vue.common.dev.js:4210:7)

    at Object.insert (https://7mooxvokz1.codesandbox.io/node_modules/vue/dist/vue.common.dev.js:3142:7)

    at invokeInsertHook (https://7mooxvokz1.codesandbox.io/node_modules/vue/dist/vue.common.dev.js:6331:28)

    at Vue.patch [as __patch__] (https://7mooxvokz1.codesandbox.io/node_modules/vue/dist/vue.common.dev.js:6548:5)

    at Vue._update (https://7mooxvokz1.codesandbox.io/node_modules/vue/dist/vue.common.dev.js:3936:19)

    at Vue.updateComponent (https://7mooxvokz1.codesandbox.io/node_modules/vue/dist/vue.common.dev.js:4057:10)

    at Watcher.get (https://7mooxvokz1.codesandbox.io/node_modules/vue/dist/vue.common.dev.js:4468:25)

    at new Watcher (https://7mooxvokz1.codesandbox.io/node_modules/vue/dist/vue.common.dev.js:4457:12)

    at mountComponent (https://7mooxvokz1.codesandbox.io/node_modules/vue/dist/vue.common.dev.js:4064:3)

    at Vue.$mount (https://7mooxvokz1.codesandbox.io/node_modules/vue/dist/vue.common.dev.js:9034:10)

    at Vue.$mount (https://7mooxvokz1.codesandbox.io/node_modules/vue/dist/vue.common.dev.js:11919:16)

    at evaluate (https://7mooxvokz1.codesandbox.io/src/main.js:46:4)

    at pe (https://codesandbox.io/static/js/sandbox.b1d596c7.js:1:163187)

    at e.value (https://codesandbox.io/static/js/sandbox.b1d596c7.js:1:177627)

    at e.value (https://codesandbox.io/static/js/sandbox.b1d596c7.js:1:205948)

    at e.value (https://codesandbox.io/static/js/sandbox.b1d596c7.js:1:205529)

    at https://codesandbox.io/static/js/sandbox.b1d596c7.js:1:101657

    at g (https://codesandbox.io/static/js/common-sandbox.7efdb2bf.chunk.js:1:475525)

    at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.7efdb2bf.chunk.js:1:475313)

    at Generator.e.(anonymous function) [as next] (https://codesandbox.io/static/js/common-sandbox.7efdb2bf.chunk.js:1:475704)

    at o (https://codesandbox.io/static/js/common-sandbox.7efdb2bf.chunk.js:1:466783)

    at i (https://codesandbox.io/static/js/common-sandbox.7efdb2bf.chunk.js:1:466993)
```

**Comment by posva** [comment]
do `const requestedPage = this.$route;` there is no `$route.path`

**Comment by ccarstens** [comment]
@adamdehaven did you find a solution? I'm running into the same problem, working on local machine but not in production.
