### ISSUE TITLE
Refused to execute script from site.com/6.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

### ISSUE THREAD

**Issue by BonBonSlick** [vuejs/vue-router#2904]
### Version
3.1.0
 
### What is expected?
Site is working 

### What is actually happening?
Errors on windows chrome. This is a bug is only for   Chrome 76 on Windows 10. Might be webpack related or something else.

---
```
site.tv/:1 Refused to execute script from 'https://site.tv/6.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
vue-router.esm.js:1905 ChunkLoadError: Loading chunk 6 failed.
(error: https://site.tv/6.js)
    at Function.requireEnsure [as e] (https://site.tv/main.js:812:26)
    at Function.fn.e (https://site.tv/main.js:156:40)
    at component (https://site.tv/main.js:9589:36)
    at https://site.tv/main.js:7654:17
    at https://site.tv/main.js:7681:66
    at Array.map (<anonymous>)
    at https://site.tv/main.js:7681:38
    at Array.map (<anonymous>)
    at flatMapComponents (https://site.tv/main.js:7680:26)
    at https://site.tv/main.js:7616:5
abort @ vue-router.esm.js:1905
(anonymous) @ vue-router.esm.js:1947
(anonymous) @ vue-router.esm.js:1768
(anonymous) @ vue-router.esm.js:1833
Promise.then (async)
(anonymous) @ vue-router.esm.js:1780
(anonymous) @ vue-router.esm.js:1801
(anonymous) @ vue-router.esm.js:1801
flatMapComponents @ vue-router.esm.js:1800
(anonymous) @ vue-router.esm.js:1736
iterator @ vue-router.esm.js:1943
step @ vue-router.esm.js:1717
step @ vue-router.esm.js:1721
(anonymous) @ vue-router.esm.js:1718
(anonymous) @ vue-router.esm.js:1964
(anonymous) @ index.js:43
iterator @ vue-router.esm.js:1943
step @ vue-router.esm.js:1717
runQueue @ vue-router.esm.js:1725
confirmTransition @ vue-router.esm.js:1972
transitionTo @ vue-router.esm.js:1874
init @ vue-router.esm.js:2494
beforeCreate @ vue-router.esm.js:540
_t @ vue.min.js:6
hn._init @ vue.min.js:6
hn @ vue.min.js:6
(anonymous) @ app.js:12
__webpack_require__ @ bootstrap:769
fn @ bootstrap:129
(anonymous) @ web.dom.iterable.js:19
__webpack_require__ @ bootstrap:769
(anonymous) @ bootstrap:907
(anonymous) @ bootstrap:907
DevTools failed to parse SourceMap: https://site.tv/5.js.map
```

**Comment by posva** [comment]
This is usually your server having a fallback to the `index.html` file for everything, including js resources. I would say there is no 6.js file in your server and it's sending back the index.html file instead.
This is a usage question that should be posted in the forums or discord chat and it's not even related to Vue Router, it's either about your server configuration or your bundler not working correctly.

**Comment by BonBonSlick** [comment]
@posva  Please note, once again, it throws error **ONLY** on wirndows chrome. 
All other platforms, browsers etc work fine. It is impossible to debug because I do not have second PC to test it. Dev  & test envs  are  linux. :(
 **Result is about -40% audience**.
dist files are:
```
bonbon@srv49167738:/var/www/ui$ ls -l dist/
total 7284
-rw-r--r-- 1 bonbon bonbon   21778 Aug 23 23:07 10.main.js
-rw-r--r-- 1 bonbon bonbon   42297 Aug 23 23:07 10.main.js.map
-rw-r--r-- 1 bonbon bonbon    9834 Aug 23 23:07 11.main.js
-rw-r--r-- 1 bonbon bonbon   13869 Aug 23 23:07 11.main.js.map
-rw-r--r-- 1 bonbon bonbon    8973 Aug 23 23:07 12.main.js
-rw-r--r-- 1 bonbon bonbon   12781 Aug 23 23:07 12.main.js.map
-rw-r--r-- 1 bonbon bonbon   45829 Aug 23 23:07 13.main.js
-rw-r--r-- 1 bonbon bonbon   54779 Aug 23 23:07 13.main.js.map
-rw-r--r-- 1 bonbon bonbon    2441 Aug 23 23:07 14.main.js
-rw-r--r-- 1 bonbon bonbon    2607 Aug 23 23:07 14.main.js.map
-rw-r--r-- 1 bonbon bonbon    3473 Aug 23 23:07 15.main.js
-rw-r--r-- 1 bonbon bonbon    5920 Aug 23 23:07 15.main.js.map
-rw-r--r-- 1 bonbon bonbon  565146 Aug 23 23:07 1.main.js
-rw-r--r-- 1 bonbon bonbon  692559 Aug 23 23:07 1.main.js.map
-rw-r--r-- 1 bonbon bonbon 1911698 Aug 23 23:07 2.main.js
-rw-r--r-- 1 bonbon bonbon 2310335 Aug 23 23:07 2.main.js.map
-rw-r--r-- 1 bonbon bonbon   30997 Aug 23 23:07 3.main.js
-rw-r--r-- 1 bonbon bonbon   41023 Aug 23 23:07 3.main.js.map
-rw-r--r-- 1 bonbon bonbon   35169 Aug 23 23:07 4.main.js
-rw-r--r-- 1 bonbon bonbon   57474 Aug 23 23:07 4.main.js.map
-rw-r--r-- 1 bonbon bonbon   21629 Aug 23 23:07 5.main.js
-rw-r--r-- 1 bonbon bonbon   28727 Aug 23 23:07 5.main.js.map
-rw-r--r-- 1 bonbon bonbon   21242 Aug 23 23:07 6.main.js
-rw-r--r-- 1 bonbon bonbon   27344 Aug 23 23:07 6.main.js.map
-rw-r--r-- 1 bonbon bonbon   16321 Aug 23 23:07 7.main.js
-rw-r--r-- 1 bonbon bonbon   21921 Aug 23 23:07 7.main.js.map
-rw-r--r-- 1 bonbon bonbon   17131 Aug 23 23:07 8.main.js
-rw-r--r-- 1 bonbon bonbon   24258 Aug 23 23:07 8.main.js.map
-rw-r--r-- 1 bonbon bonbon   12617 Aug 23 23:07 9.main.js
-rw-r--r-- 1 bonbon bonbon   15161 Aug 23 23:07 9.main.js.map
drwxr-xr-x 2 bonbon bonbon    4096 Aug 21 13:51 fonts
-rw-r--r-- 1 bonbon bonbon    1845 Aug 23 23:07 index.html
-rw-r--r-- 1 bonbon bonbon  552296 Aug 23 23:07 main.js
-rw-r--r-- 1 bonbon bonbon  710445 Aug 23 23:07 main.js.map
drwxr-xr-x 4 bonbon bonbon    4096 Aug 21 13:51 static

```

webpack config
```

module.exports = {
    mode: 'production',
    entry: [
        './src/app.js',
    ],
    output: {
        path: path.resolve(__dirname, '../dist'),
        filename: 'main.js',
        publicPath: '/',
    },
    module: {
        rules: [
            {
                test: /\.vue$/,
                loader: 'vue-loader',
                options: {
                    loaders: {
                        // Since sass-loader (weirdly) has SCSS as its default parse mode, we map
                        // the "scss" and "sass" values for the lang attribute to the right configs here.
                        // other preprocessors should work out of the box, no loader config like this necessary.
                        scss: 'vue-style-loader!css-loader!sass-loader', // <style lang="scss">
                        sass: 'vue-style-loader!css-loader!sass-loader?indentedSyntax', // <style lang="sass">
                    },
                },
            },
            {
                test: /\.js$/,
                use: 'babel-loader',
                exclude: /node_modules/,
            },
            {
                test: /\.css$/,
                use: [
                    'vue-style-loader',
                    'style-loader',
                    'css-loader',
                ],
            },
            {
                test: /\.scss$/,
                use: [
                    {
                        loader: 'style-loader',
                    },
                    {
                        loader: 'css-loader',
                    },
                    {
                        loader: 'sass-loader',
                    },
                ],
            },
            {
                test: /\.(png|jpg)$/,
                loader: 'file-loader',
                options: {
                    name: '[name].[ext]?[hash]',
                },
            },
            {
                test: /\.(otf|eot|woff|woff2|ttf|svg)$/,
                use: [
                    {
                        loader: 'file-loader',
                        options: {
                            name: '[name].[ext]',
                            outputPath: 'fonts/',
                        },
                    },
                ],
            },
        ],
    },
    plugins: [
        new VueLoaderPlugin(),
        new webpack.HotModuleReplacementPlugin(),
        new webpack.NoEmitOnErrorsPlugin(),
        new CopyWebpackPlugin([
            {
                from: path.join(__dirname, '../static'),
                to: path.join(__dirname, '../dist/static'),
                // ignore: ['.*'],
            },
        ]),
        new HtmlWebpackPlugin({
            filename: 'index.html',
            template: 'index.html',
            inject: true,
        }),
    ],
    resolve: {
        extensions: ['.js', '.vue', '.json'],
        alias: {
            config: path.resolve(__dirname, '../config'),
            vue: 'vue/dist/vue.min.js',
        },
    },
    optimization: {
        minimizer: [
            // we specify a custom UglifyJsPlugin here to get source maps in production
            new UglifyJsPlugin({
                include: /\.min\.js$/,
                sourceMap: true,
                cache: true,
                parallel: true,
                uglifyOptions: {
                    compress: false,
                    warnings: true,
                    ecma: 6,
                    mangle: true,
                },
            }),
        ],
    },
    performance: {hints: false},
};
module.exports.devtool = '#source-map';
module.exports.plugins = (module.exports.plugins || []).concat([
    new webpack.DefinePlugin({
        'process.env': {
            NODE_ENV: '"production"',
            API_URL: '"https://api.test.tv"',
        },
    }),
    new webpack.LoaderOptionsPlugin({
        minimize: true,
    }),
]);

```

nginx
```

server {
        listen 443 ssl http2;
        listen [::]:443 ssl http2;

        server_name test.tv www.test.tv;

        root /var/www/ui/dist;
        index index.html index.htm;

        include /etc/letsencrypt/options-ssl-nginx.conf;

        access_log /var/log/nginx/access.test.tv.log;
        error_log /var/log/nginx/error.test.tv.log;

// ACCORDING TO DOCS
        location / {
                root /var/www/ui/dist;
                try_files $uri $uri/ /index.html;

                #try_files $uri $uri/ @rewrites;
        }

        location @rewrites {
                rewrite ^(.+)$ /index.html last;
        }

        location ~ /\.ht {
                deny all;
        }

}


```

Saw vue forum, most of the users are Chinese, I do not know Chinese. Google can not translate it. In addition, forum question might never receive an answer.

**Comment by posva** [comment]
Issues are not for questions, I don't know how to make it clearer... On top of that, this is not even related to Vue Router, it's an SPA question

The forum has more activity in English than in Chinese, it has activity in many languages so people can use their language. Most of the posts get answers, if you never post it, it will never be able to receive an answer, that's for sure

**Comment by BonBonSlick** [comment]
I do not know what exactly it was, after a couple of weeks, and packages updates issue disappeared. It could be chrome issue, router, js, some package, whatever. Issue can be closed, probably could be resolved by rolling back to very old versions and old code. Thank you for your time.
