### ISSUE TITLE
Cannot read property '_normalized' of undefined   

### ISSUE THREAD

**Issue by tomderudder** [vuejs/vue-router#3021]
### Version
3.0.7

### Reproduction link
[https://fr.nuxtjs.org/api/configuration-generate/](https://fr.nuxtjs.org/api/configuration-generate/)

### Steps to reproduce
yarn run generate or npm run generate in nuxt project

### What is expected?
TypeError: Cannot read property '_normalized' of undefined
    at normalizeLocation

### What is actually happening?
build

**Comment by posva** [comment]
this is vue-router's repo, not Nuxt's. You should open an issue there (with a proper) and come back if it turns out to be a vue-router bug but please provide a boiled down repro with no nuxt when opening a bug report

**Comment by RossComputerGuy** [comment]
I'm experiencing the same problem with Vue and not Nuxt. This is the stack trace:
```
TypeError: Cannot read property '_normalized' of undefined
    at normalizeLocation (/home/ross/emberliteOS/website/node_modules/vue-router/dist/vue-router.common.js:971:12)
    at Object.match (/home/ross/emberliteOS/website/node_modules/vue-router/dist/vue-router.common.js:1493:20)
    at VueRouter.match (/home/ross/emberliteOS/website/node_modules/vue-router/dist/vue-router.common.js:2852:23)
    at AbstractHistory.transitionTo (/home/ross/emberliteOS/website/node_modules/vue-router/dist/vue-router.common.js:2146:25)
    at AbstractHistory.push (/home/ross/emberliteOS/website/node_modules/vue-router/dist/vue-router.common.js:2750:10)
    at /home/ross/emberliteOS/website/node_modules/vue-router/dist/vue-router.common.js:2952:22
    at new Promise (<anonymous>)
    at VueRouter.push (/home/ross/emberliteOS/website/node_modules/vue-router/dist/vue-router.common.js:2951:12)
    at server.js:334:12
    at new Promise (<anonymous>)
```

**Comment by n4an** [comment]
yesterday works well today not

**Comment by zhangweida1995** [comment]
How did you solve it?

**Comment by PLQin** [comment]
删除掉 `layouts\default.vue` 中的 `script` 试试 

<small>Try deleting the 'script' in 'layouts\default.vue'</small>

**Comment by yuta-san** [comment]
I got same error, when router-link :to was undefined. Check this value.
```
<router-link :to="undefined">AAAA</router-link>
```
