### ISSUE TITLE
ChunkLoadError: Loading chunk chunk-x failed.

### ISSUE THREAD

**Issue by MatanYadaev** [vuejs/vue-router#3257]
### Version
3.3.2

I'm using the latest Vue versions with Vue Router, and Vue Composition API.
Since I deployed my project, I catch every few days (I guess, every deployment), a `ChunkLoadError` exception in Sentry.

I'm not sure why it happens, I don't have any custom Webpack configurations.

This is the exception:
```
ChunkLoadError: Loading chunk chunk-626fe0ff failed.
(timeout: https://example.com/js/chunk-626fe0ff.248f3eae.js)
  at (timeout: (/js/chunk-626fe0ff.248f3eae.js))
  at Function.s.e(webpack/bootstrap:126:18)
  at cb(src/pages/Inquiry.vue:67:1)
  at apply(./node_modules/@vue/composition-api/dist/vue-composition-api.module.js:932:9)
  at index(./node_modules/@vue/composition-api/dist/vue-composition-api.module.js:891:20)
  at flushQueue(./node_modules/@vue/composition-api/dist/vue-composition-api.module.js:818:15)
  at call(./node_modules/@vue/composition-api/dist/vue-composition-api.module.js:830:17)
  at i(./node_modules/vue/dist/vue.runtime.esm.js:1980:12)
  at flushCallbacks(./node_modules/vue/dist/vue.runtime.esm.js:1906:12)
```

The weird part is that the chunk file still exists, so I'm not sure what this exception is about. Any guidance, what should I check? It happens in production only, not locally. I'm using Amazon Amplify to host the app.

**Comment by posva** [comment]
Please use the proper channels to ask questions. The request goes to example.com, so you probably have something wrong in a base tag?

**Comment by MatanYadaev** [comment]
@posva I changed the original URL to `example.com` in the exception example

**Comment by MatanYadaev** [comment]
@posva Any idea?

**Comment by RezaErfani67** [comment]
this happen for me when I use http2 protocol in build production...

![image](https://user-images.githubusercontent.com/24381986/110211202-b750d480-7eaa-11eb-866a-5a94757b1952.png)

![image](https://user-images.githubusercontent.com/24381986/110211185-a99b4f00-7eaa-11eb-998f-f4d60fb5f6dc.png)
