### ISSUE TITLE
examples warning

### ISSUE THREAD

**Issue by xiecg** [vuejs/vue-router#901]
Hi, all.

`
resolve failed:  { Error: Cannot find module 'nightwatch-helpers'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.requireRelative.resolve (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/require-relative/0.8.7/require-relative/index.js:30:17)
    at resolve (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:26:26)
    at findAndRemove (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:83:11)
    at /Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:126:13
    at Array.map (native)
    at loadPreset (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:118:29)
    at module.exports (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/index.js:95:19)
    at Object.<anonymous> (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/babel-preset-es2015-loose/8.0.0/babel-preset-es2015-loose/index.js:5:18)
    at Module._compile (module.js:573:32) code: 'MODULE_NOT_FOUND' } nightwatch-helpers
resolve failed:  { Error: Cannot find module 'nightwatch-helpers'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.requireRelative.resolve (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/require-relative/0.8.7/require-relative/index.js:30:17)
    at resolve (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:26:26)
    at findAndRemove (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:83:11)
    at /Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:126:13
    at Array.map (native)
    at loadPreset (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:118:29)
    at module.exports (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/index.js:95:19)
    at Object.<anonymous> (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/babel-preset-es2015-loose/8.0.0/babel-preset-es2015-loose/index.js:5:18)
    at Module._compile (module.js:573:32) code: 'MODULE_NOT_FOUND' } nightwatch-helpers
resolve failed:  { Error: Cannot find module 'nightwatch-helpers'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.requireRelative.resolve (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/require-relative/0.8.7/require-relative/index.js:30:17)
    at resolve (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:26:26)
    at findAndRemove (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:83:11)
    at /Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:126:13
    at Array.map (native)
    at loadPreset (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:118:29)
    at module.exports (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/index.js:95:19)
    at Object.<anonymous> (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/babel-preset-es2015-loose/8.0.0/babel-preset-es2015-loose/index.js:5:18)
    at Module._compile (module.js:573:32) code: 'MODULE_NOT_FOUND' } nightwatch-helpers
resolve failed:  { Error: Cannot find module 'nightwatch-helpers'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.requireRelative.resolve (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/require-relative/0.8.7/require-relative/index.js:30:17)
    at resolve (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:26:26)
    at findAndRemove (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:83:11)
    at /Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:126:13
    at Array.map (native)
    at loadPreset (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:118:29)
    at module.exports (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/index.js:95:19)
    at Object.<anonymous> (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/babel-preset-es2015-loose/8.0.0/babel-preset-es2015-loose/index.js:5:18)
    at Module._compile (module.js:573:32) code: 'MODULE_NOT_FOUND' } nightwatch-helpers
resolve failed:  { Error: Cannot find module 'nightwatch-helpers'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.requireRelative.resolve (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/require-relative/0.8.7/require-relative/index.js:30:17)
    at resolve (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:26:26)
    at findAndRemove (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:83:11)
    at /Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:126:13
    at Array.map (native)
    at loadPreset (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:118:29)
    at module.exports (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/index.js:95:19)
    at Object.<anonymous> (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/babel-preset-es2015-loose/8.0.0/babel-preset-es2015-loose/index.js:5:18)
    at Module._compile (module.js:573:32) code: 'MODULE_NOT_FOUND' } nightwatch-helpers
resolve failed:  { Error: Cannot find module 'nightwatch-helpers'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.requireRelative.resolve (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/require-relative/0.8.7/require-relative/index.js:30:17)
    at resolve (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:26:26)
    at findAndRemove (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:83:11)
    at /Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:126:13
    at Array.map (native)
    at loadPreset (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:118:29)
    at module.exports (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/index.js:95:19)
    at Object.<anonymous> (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/babel-preset-es2015-loose/8.0.0/babel-preset-es2015-loose/index.js:5:18)
    at Module._compile (module.js:573:32) code: 'MODULE_NOT_FOUND' } nightwatch-helpers
resolve failed:  { Error: Cannot find module 'nightwatch-helpers'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.requireRelative.resolve (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/require-relative/0.8.7/require-relative/index.js:30:17)
    at resolve (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:26:26)
    at findAndRemove (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:83:11)
    at /Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:126:13
    at Array.map (native)
    at loadPreset (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:118:29)
    at module.exports (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/index.js:95:19)
    at Object.<anonymous> (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/babel-preset-es2015-loose/8.0.0/babel-preset-es2015-loose/index.js:5:18)
    at Module._compile (module.js:573:32) code: 'MODULE_NOT_FOUND' } nightwatch-helpers
resolve failed:  { Error: Cannot find module 'nightwatch-helpers'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.requireRelative.resolve (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/require-relative/0.8.7/require-relative/index.js:30:17)
    at resolve (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:26:26)
    at findAndRemove (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:83:11)
    at /Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:126:13
    at Array.map (native)
    at loadPreset (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:118:29)
    at module.exports (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/index.js:95:19)
    at Object.<anonymous> (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/babel-preset-es2015-loose/8.0.0/babel-preset-es2015-loose/index.js:5:18)
    at Module._compile (module.js:573:32) code: 'MODULE_NOT_FOUND' } nightwatch-helpers
resolve failed:  { Error: Cannot find module 'nightwatch-helpers'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.requireRelative.resolve (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/require-relative/0.8.7/require-relative/index.js:30:17)
    at resolve (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:26:26)
    at findAndRemove (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:83:11)
    at /Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:126:13
    at Array.map (native)
    at loadPreset (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:118:29)
    at module.exports (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/index.js:95:19)
    at Object.<anonymous> (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/babel-preset-es2015-loose/8.0.0/babel-preset-es2015-loose/index.js:5:18)
    at Module._compile (module.js:573:32) code: 'MODULE_NOT_FOUND' } nightwatch-helpers
resolve failed:  { Error: Cannot find module 'nightwatch-helpers'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.requireRelative.resolve (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/require-relative/0.8.7/require-relative/index.js:30:17)
    at resolve (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:26:26)
    at findAndRemove (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:83:11)
    at /Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:126:13
    at Array.map (native)
    at loadPreset (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:118:29)
    at module.exports (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/index.js:95:19)
    at Object.<anonymous> (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/babel-preset-es2015-loose/8.0.0/babel-preset-es2015-loose/index.js:5:18)
    at Module._compile (module.js:573:32) code: 'MODULE_NOT_FOUND' } nightwatch-helpers
resolve failed:  { Error: Cannot find module 'nightwatch-helpers'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.requireRelative.resolve (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/require-relative/0.8.7/require-relative/index.js:30:17)
    at resolve (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:26:26)
    at findAndRemove (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:83:11)
    at /Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:126:13
    at Array.map (native)
    at loadPreset (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:118:29)
    at module.exports (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/index.js:95:19)
    at Object.<anonymous> (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/babel-preset-es2015-loose/8.0.0/babel-preset-es2015-loose/index.js:5:18)
    at Module._compile (module.js:573:32) code: 'MODULE_NOT_FOUND' } nightwatch-helpers
resolve failed:  { Error: Cannot find module 'nightwatch-helpers'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.requireRelative.resolve (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/require-relative/0.8.7/require-relative/index.js:30:17)
    at resolve (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:26:26)
    at findAndRemove (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:83:11)
    at /Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:126:13
    at Array.map (native)
    at loadPreset (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:118:29)
    at module.exports (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/index.js:95:19)
    at Object.<anonymous> (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/babel-preset-es2015-loose/8.0.0/babel-preset-es2015-loose/index.js:5:18)
    at Module._compile (module.js:573:32) code: 'MODULE_NOT_FOUND' } nightwatch-helpers
resolve failed:  { Error: Cannot find module 'nightwatch-helpers'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.requireRelative.resolve (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/require-relative/0.8.7/require-relative/index.js:30:17)
    at resolve (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:26:26)
    at findAndRemove (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:83:11)
    at /Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:126:13
    at Array.map (native)
    at loadPreset (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:118:29)
    at module.exports (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/index.js:95:19)
    at Object.<anonymous> (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/babel-preset-es2015-loose/8.0.0/babel-preset-es2015-loose/index.js:5:18)
    at Module._compile (module.js:573:32) code: 'MODULE_NOT_FOUND' } nightwatch-helpers
resolve failed:  { Error: Cannot find module 'nightwatch-helpers'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.requireRelative.resolve (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/require-relative/0.8.7/require-relative/index.js:30:17)
    at resolve (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:26:26)
    at findAndRemove (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:83:11)
    at /Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:126:13
    at Array.map (native)
    at loadPreset (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:118:29)
    at module.exports (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/index.js:95:19)
    at Object.<anonymous> (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/babel-preset-es2015-loose/8.0.0/babel-preset-es2015-loose/index.js:5:18)
    at Module._compile (module.js:573:32) code: 'MODULE_NOT_FOUND' } nightwatch-helpers
resolve failed:  { Error: Cannot find module 'nightwatch-helpers'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.requireRelative.resolve (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/require-relative/0.8.7/require-relative/index.js:30:17)
    at resolve (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:26:26)
    at findAndRemove (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:83:11)
    at /Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:126:13
    at Array.map (native)
    at loadPreset (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:118:29)
    at module.exports (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/index.js:95:19)
    at Object.<anonymous> (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/babel-preset-es2015-loose/8.0.0/babel-preset-es2015-loose/index.js:5:18)
    at Module._compile (module.js:573:32) code: 'MODULE_NOT_FOUND' } nightwatch-helpers
resolve failed:  { Error: Cannot find module 'nightwatch-helpers'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.requireRelative.resolve (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/require-relative/0.8.7/require-relative/index.js:30:17)
    at resolve (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:26:26)
    at findAndRemove (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:83:11)
    at /Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:126:13
    at Array.map (native)
    at loadPreset (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:118:29)
    at module.exports (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/index.js:95:19)
    at Object.<anonymous> (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/babel-preset-es2015-loose/8.0.0/babel-preset-es2015-loose/index.js:5:18)
    at Module._compile (module.js:573:32) code: 'MODULE_NOT_FOUND' } nightwatch-helpers
resolve failed:  { Error: Cannot find module 'nightwatch-helpers'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.requireRelative.resolve (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/require-relative/0.8.7/require-relative/index.js:30:17)
    at resolve (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:26:26)
    at findAndRemove (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:83:11)
    at /Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:126:13
    at Array.map (native)
    at loadPreset (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:118:29)
    at module.exports (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/index.js:95:19)
    at Object.<anonymous> (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/babel-preset-es2015-loose/8.0.0/babel-preset-es2015-loose/index.js:5:18)
    at Module._compile (module.js:573:32) code: 'MODULE_NOT_FOUND' } nightwatch-helpers
resolve failed:  { Error: Cannot find module 'nightwatch-helpers'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.requireRelative.resolve (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/require-relative/0.8.7/require-relative/index.js:30:17)
    at resolve (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:26:26)
    at findAndRemove (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:83:11)
    at /Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:126:13
    at Array.map (native)
    at loadPreset (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:118:29)
    at module.exports (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/index.js:95:19)
    at Object.<anonymous> (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/babel-preset-es2015-loose/8.0.0/babel-preset-es2015-loose/index.js:5:18)
    at Module._compile (module.js:573:32) code: 'MODULE_NOT_FOUND' } nightwatch-helpers
resolve failed:  { Error: Cannot find module 'nightwatch-helpers'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.requireRelative.resolve (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/require-relative/0.8.7/require-relative/index.js:30:17)
    at resolve (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:26:26)
    at findAndRemove (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:83:11)
    at /Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:126:13
    at Array.map (native)
    at loadPreset (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:118:29)
    at module.exports (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/index.js:95:19)
    at Object.<anonymous> (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/babel-preset-es2015-loose/8.0.0/babel-preset-es2015-loose/index.js:5:18)
    at Module._compile (module.js:573:32) code: 'MODULE_NOT_FOUND' } nightwatch-helpers
resolve failed:  { Error: Cannot find module 'nightwatch-helpers'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.requireRelative.resolve (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/require-relative/0.8.7/require-relative/index.js:30:17)
    at resolve (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:26:26)
    at findAndRemove (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:83:11)
    at /Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:126:13
    at Array.map (native)
    at loadPreset (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:118:29)
    at module.exports (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/index.js:95:19)
    at Object.<anonymous> (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/babel-preset-es2015-loose/8.0.0/babel-preset-es2015-loose/index.js:5:18)
    at Module._compile (module.js:573:32) code: 'MODULE_NOT_FOUND' } nightwatch-helpers
resolve failed:  { Error: Cannot find module 'nightwatch-helpers'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.requireRelative.resolve (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/require-relative/0.8.7/require-relative/index.js:30:17)
    at resolve (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:26:26)
    at findAndRemove (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:83:11)
    at /Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:126:13
    at Array.map (native)
    at loadPreset (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/lib/serialize.js:118:29)
    at module.exports (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/modify-babel-preset/3.2.0/modify-babel-preset/index.js:95:19)
    at Object.<anonymous> (/Users/xiecg/Desktop/vue-router/node_modules/.npminstall/babel-preset-es2015-loose/8.0.0/babel-preset-es2015-loose/index.js:5:18)
    at Module._compile (module.js:573:32) code: 'MODULE_NOT_FOUND' } nightwatch-helpers
`

How to solve ?

**Comment by posva** [comment]
do `npm install` or `yarn` at the root of the project. You're just missing a dependency

**Comment by xiecg** [comment]
@posva 

Thank you for reply, problem solved.
